CREATE TABLE IF NOT EXISTS `HV_TIPPSPIEL_TEAMS` (
  `TeamID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Name` varchar(25) COLLATE latin1_german2_ci NOT NULL,
  `NameShort` varchar(3) COLLATE latin1_german2_ci NOT NULL,
  PRIMARY KEY (`TeamID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci AUTO_INCREMENT=32 ;

INSERT INTO `HV_TIPPSPIEL_TEAMS` (`TeamID`, `Name`, `NameShort`) VALUES
(1, 'Ägypten', 'EGY'),
(2, 'Argentinien', 'ARG'),
(3, 'Australien', 'AUS'),
(4, 'Belgien', 'BEL'),
(5, 'Brasilien', 'BRA'),
(6, 'Costa Rica', 'CRC'),
(7, 'Dänemark', 'DEN'),
(8, 'Deutschland', 'GER'),
(9, 'England', 'ENG'),
(10, 'Frankreich', 'FRA'),
(11, 'Iran', 'IRN'),
(12, 'Island', 'ISL'),
(13, 'Japan', 'JPN'),
(14, 'Kolumbien', 'COL'),
(15, 'Korea Republik', 'KOR'),
(16, 'Kroatien', 'CRO'),
(17, 'Marokko', 'MAR'),
(18, 'Mexiko', 'MEX'),
(19, 'Nigeria', 'NGA'),
(20, 'Panama', 'PAN'),
(21, 'Peru', 'PER'),
(22, 'Polen', 'POL'),
(23, 'Portugal', 'POR'),
(24, 'Russland', 'RUS'),
(25, 'Saudiarabien', 'KSA'),
(26, 'Schweden', 'SWE'),
(27, 'Schweiz', 'SUI'),
(28, 'Senegal', 'SEN'),
(29, 'Serbien', 'SRB'),
(30, 'Spanien', 'ESP'),
(31, 'Tunesien', 'TUN'),
(32, 'Urugay', 'URU');
